JS Support for substrait
substrait-io/substrait-js pull request #1
Opened 2023-04-17 14:03 UTC by sanjibansg

This PR adds the initial implementation for substrait-js. It facilitates downloading the substrait specifications and packaging them to a static `.js` module, and a parser for reading substrait plans.

2023-04-27 18:46 UTC, westonpace requested changes
This doesn't actually create something that you can import and use.  As an example, you can run `npm pack` to generate a package and then try and import that package into a test project (for example, https://github.com/westonpace/substrait-js-test)

I've created a PR that shakes things up a little and should make it usable as a package.

2023-04-27 18:46 UTC, westonpace commented on README.md
> +[Apache-2.0 license](https://github.com/sanjibansg/substrait-fiddle-backend/blob/main/LICENSE)
```suggestion
[Apache-2.0 license](https://www.apache.org/licenses/LICENSE-2.0)
```

2023-04-27 18:46 UTC, westonpace commented on .npmignore
> +dist/
I don't think we can ignore `dist/` here.  Don't we want it to be part of the package?

2023-04-27 18:46 UTC, westonpace commented on package.json
> +  "description": "Packages Substrait protobuf files into a static module.",
```suggestion
  "description": "Utilities for working with Substrait plans in Javascript projects",
```
Now that the parser, etc. are part of this package I think we can update this description.

2023-04-27 18:46 UTC, westonpace commented on package.json
> +    "proto": "pbjs --target static-module --path substrait-spec/proto -o dist/index.js substrait/plan.proto",
This refers to `substrait-spec` which appears to be a missing submodule.  Did you forget to checking the submodules files?

2023-04-27 18:46 UTC, westonpace commented on package.json
> +  "version": "0.20.0",
Let's change this to 0.1.0.  Now that we are no longer downloading substrait with a script I don't think we need to mirror the version.  Also, now that we have independent js code (like parser.ts) we need to have our own version number.

2023-04-27 18:46 UTC, westonpace commented on src/parser.ts
> +    idCounters: Map<string, number>
Now that we are in typescript we have the ability to mark things as private.  These instance variables, and most of the methods, should be marked private.

2023-04-28 07:27 UTC, sanjibansg commented on README.md
> +[Apache-2.0 license](https://github.com/sanjibansg/substrait-fiddle-backend/blob/main/LICENSE)
Made the change, thanks!

2023-04-28 07:27 UTC, sanjibansg commented on package.json
> +  "description": "Packages Substrait protobuf files into a static module.",
Made the change, thanks!

2023-04-28 07:27 UTC, sanjibansg commented on package.json
> +  "version": "0.20.0",
Made the change, thanks!

2023-04-28 07:28 UTC, sanjibansg commented on .npmignore
> +dist/
Yes, right. I did that by mistake, it should only be ignored for git. Thanks for pointing that out.

2023-04-28 08:52 UTC, sanjibansg commented on src/parser.ts
> +    idCounters: Map<string, number>
Made the change, thanks!

2023-05-01 09:55 UTC, sanjibansg commented on package.json
> +    "proto": "pbjs --target static-module --path substrait-spec/proto -o dist/index.js substrait/plan.proto",
Yes, sorry, missed that. I am guessing it was because it was marked in the `.gitignore` file. Thanks for pointing it out!

2023-05-15 17:01 UTC, westonpace requested changes
I still need to go through the parser.ts stuff with a bit more of a fine look but here are some top level comments.  Also, let's move the D3 work into a follow-on PR so we can keep this PR focused on the parser.

2023-05-15 17:01 UTC, westonpace commented on package.json
> +    "d3": "^7.8.4",
Can we keep the d3 / visualization component for a follow-up PR?  Just in the interest of size.

2023-05-15 17:01 UTC, westonpace commented on .eslintrc.js
> +module.exports = {
Let's add a follow-up issue/task to hook eslint, etc. into CI.

2023-05-15 17:01 UTC, westonpace commented on .npmignore
> +scripts/
Do we have a scripts folder anymore?

2023-05-15 17:01 UTC, westonpace commented on README.md
> +JS support for Substrait.
Let's mention here that we have typings so it can be used with TS.  We might also want to give a brief definition of what substrait is.

2023-05-15 17:01 UTC, westonpace commented on README.md
> +## Installation
Is this for developers of substrait-js?  Or for users of substrait-js?  I don't think users would need to clone the github repo.

2023-05-15 17:01 UTC, westonpace commented on README.md
> +npm install
Might want to suggest `npm ci` instead of `npm install`.

2023-05-15 17:01 UTC, westonpace commented on README.md
> +```
Let's document the build step.

2023-05-15 17:01 UTC, westonpace commented on src/parser.ts
> +   */
Let's move these to match up with the interfaces at the top.

2023-05-15 17:01 UTC, westonpace commented on src/parser.ts
> +   * and uknown nullability
```suggestion
   * and unknown nullability
```

2023-05-15 17:01 UTC, westonpace commented on src/parser.ts
> +      }));
Should these be getting added to `props`?

2023-05-15 17:01 UTC, westonpace commented on src/parser.ts
> +  private expressionToStr(expr:substrait.IExpression, exprIn:Field) {
Let's create a follow-up issue to handle expressions that cannot be easily converted to strings (e.g. subqueries)

2023-05-19 14:44 UTC, sanjibansg commented on package.json
> +    "d3": "^7.8.4",
Removed the d3 visualization stuff. Will make a follow-up PR for them.

2023-05-19 14:47 UTC, sanjibansg commented on .eslintrc.js
> +module.exports = {
https://github.com/substrait-io/substrait-js/issues/2

made an issue to track CI checks for eslint and build.

2023-05-19 14:50 UTC, sanjibansg commented on .npmignore
> +scripts/
Sorry, it is no longer required. Removed it now. Thanks for pointing it out!

2023-05-19 14:51 UTC, sanjibansg commented on README.md
> +npm install
made the change, thanks for suggesting!

2023-05-19 14:52 UTC, sanjibansg commented on README.md
> +```
added the build step instruction. Thanks for pointing that out!

2023-05-19 14:53 UTC, sanjibansg commented on src/parser.ts
> +   * and uknown nullability
corrected that, thanks!

2023-05-19 14:56 UTC, sanjibansg commented on src/parser.ts
> +  private expressionToStr(expr:substrait.IExpression, exprIn:Field) {
Created issue https://github.com/substrait-io/substrait-js/issues/3

2023-05-19 15:06 UTC, sanjibansg commented on README.md
> +## Installation
yes, that's right, it is only for developers.

2023-05-19 15:09 UTC, sanjibansg commented on README.md
> +## Installation
Rephrased it to `Development setup`

2023-05-19 15:18 UTC, sanjibansg commented on src/parser.ts
> +   */
made the change, thanksz

2023-05-19 15:35 UTC, sanjibansg commented on README.md
> +JS support for Substrait.
updated readme. Do suggest if it needs any further changes.

2023-05-23 05:58 UTC, sanjibansg commented on src/parser.ts
> +      }));
Yes, made the change, thanks!

2023-06-06 13:40 UTC, westonpace approved these changes

2023-06-06 13:41 UTC, merged